[package]
name = "updater"
version = "2.2.2"
authors = ["Jai"]
edition = "2021"
description = "A tool to update Minecraft servers."


[profile.release]
opt-level = "z"  # Optimize for size.
strip = true  # Automatically strip symbols from the binary.
lto = true
codegen-units = 1

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.18", features = ["blocking", "json", "brotli"] }
serde = { version = "1.0.178", features = ["derive"] }
serde_json = "1.0.104"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
clap = { version = "4.3.19", features = ["derive"] }
sha2 = "0.10.7"
md-5 = "0.10.5"
thiserror = "1.0.44"
anyhow = "1.0.72"
